global:
  repository: "twister22"
  pullPolicy: IfNotPresent
  namespace: "quiz-time"
  MYSQL_DATABASE_NAME: "quiz_time"
  MYSQL_DATABASE_USERNAME: "twister"
  MYSQL_DATABASE_PASSWORD: "soni@123"
  MYSQL_DATABASE_URL: "mysql-service"

quiz_time:
  replicaCount: 1
  name: "quiz-time"
  image:
    url: "quiz-time"
    tag: "latest"
  service:
    type: NodePort
    port: "8081"

mysql:
  replicaCount: 1
  name: "mysql-deployment"
  image:
    url: "mysql"
    tag: "5.7"
  service:
    type: ClusterIP
    port: "3306"
  pvc:
    claim_name: "mysql-pvc"
    storage_class: "system"
    volume_access_mode: "ReadWriteMany"
  MYSQL_DATABASE_ROOT_PASSWORD: "1653"